# For a random string in random case, print the string in lower, upper, capitalized and title case
a = input("Enter a word with random case: ")
a = a.lower()
print("Lower Case: ",a)
a = a.upper()
print("Upper Case: ",a)
a = a.capitalize()
print("Capitalized case: ",a)
a = a.title()
print("Title Case: ",a)